# --- SEAC specific parameters ---
action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0005

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

mac: "exp_sharing_mac"
agent: "rnn_ns"
agent_output_type: "pi_logits"
learner: "seac_learner"
critic_type: "ac_critic_es"
seac_lambda: 1.0
seac_retrace_is: False
entropy_coef: 0.001
standardise_returns: False
standardise_rewards: True
use_rnn: False
q_nstep: 5 # 1 corresponds to normal r + gammaV
name: "seac"

t_max: 20050000
